### ISSUE TITLE
[Omnibus] Roadmap for the coming weeks

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#165]
Let's use this issue to record the changes we are planning for OptMeowt in the coming weeks. Feel free to add/change anything as need be! Let's also keep this as a very high level overview, we should open sub-issues for every item here. 

As mentioned, @kbeliauski, @stanleymarkman, @SebastianZimmeck and I agreed on a general road map for the planned changes in today's meeting.  

**Overarching Topics** 
- [x]  Overall architecture / Rewriting the current extension
- [ ] Developing the analysis components
- [ ] React / Frontend
- [x] Database vs. Local storage
- [ ] UI / UX differences for Firefox & Chrome versions

**Chrome vs. Firefox Implementations**
As a side note regarding supported web browsers: We intend to rewrite the current code base in a modularized fashion (will be addressed in an Overall Architecture issue) which should essentially be a copy of the extension at this point in time. From here, we will develop our analysis work only for Firefox and this version will diverge from the Chrome version we will have refactored. This will ideally allow us to keep one repo for two versions of the extension, however with more functionality in our Firefox version. 

Here is a photo of our notes from our meeting for reference: 

<img src="https://user-images.githubusercontent.com/60238705/120717434-87a76d80-c495-11eb-921a-feda3ffb3e1f.png" width="600">

Let's get to it! 🚀

**Comment by SebastianZimmeck** [comment]
Nice! On Chrome vs. Firefox, (1) the opt out functionality will be available for Chrome and Firefox and (2) the compliance analysis functionality only for Firefox. This will be reflected in our modularized approach.

**Comment by SebastianZimmeck** [comment]
@kalicki1, can you update this issue (or close if it is superseded in the meantime)?

**Comment by kalicki1** [comment]
I think that we have clarified our timeline sufficiently enough since I opened this issue so that we can close this one. 

The way I see it, we will be done with refactoring the code very soon and we will be able to move onto designing and implementing the analysis functionality. Since this is the case, I will go ahead and close this omnibus!
