### ISSUE TITLE
Updating the Domain List as technology agnostic To-Do

### ISSUE THREAD

**Issue by kalicki1** [privacy-tech-lab/optmeowt-browser-extension#56]
During our meeting today, @SebastianZimmeck and I discussed the current OptMeowt UI and the user experience it provides. We decided it needs a major revamping, which is outlined below: 

- [x] Update the 'whitelist' language to 'Domain List,' since it will be technology agnostic and will not need to specify what technologies you are switching on/off.
- [x] Update the default Domain List mode to send a Do Not Sell Signal (So the switch will be green in the popup)
- [x] Add `delete` button functionality. 
- [ ] Add `+` button functionality. 
- [x] Update the Popup language to specify `enabled` or `disabled`. 
- [x] Update the Domain List to remove the toggles, and use the checkboxes as 'turning off' the Do Not Sell for given sites. This will be an 'inverse' of what it will show now. 
- [ ] **Deleting cookies:** Make sure all cookies (`usprivacy`, DAA, and custom cookies) are removed for the given domain when a user shuts them off. Register a popup notifying them they should refresh the extension to replace opt out cookies if they switch them back on (issue #62).
- [ ] **Adding cookies back in:** Add functionality that will iterate over all stored cookies (DAA list, custom cookie list, local storage, etc. ) to replace all cookies automatically if a user opts back in to Do Not Sell for an ad network or otherwise. 
- [x] Switch back to green toggles for consistency between the popup window toggle and the Domain List toggle
- [ ] Add filtering options to the Domain List
- [ ] Add a 'Do Not Sell Active' or other similar column categorization to the sticky Domain List navbar

This covers language elements (issue #55), UI elements (Domain List page & popup), and Domain List extension functionality (list toggles all technologies).

**Comment by kalicki1** [comment]
I will work on this issue from within branch #58, since this is a broken down subset of what needs to be accomplished there.

**Comment by kalicki1** [comment]
Most of the major functionality from this issue has been implemented in the most recent commits from branch issue #58. What's left was opened up in issue #62 and the few remaining things that could be added are optional UI elements. For the most part, I believe this issue can be closed and merged into the master branch.

**Comment by SebastianZimmeck** [comment]
Sounds good! Feel free to close whenever ready, @kalicki1.
